language: bash
sudo: required
cache: apt

# we don't use docker but this triggers travis-ci to provide Ubuntu 14.04
services:
    - docker
before_install:
    - lsb_release -a
    - sudo apt-get update -qq
install:
    - sudo make dependencies
    - make local
script:    
    # make test and create Debian package
    - make package
    # locally install package
    - sudo dpkg -i cocoda-db_*.deb
    - sudo service cocoda-db status
    # test against localhost
    - export TEST_URL=6033
    - prove -Ilocal/lib/perl5 -v # requires Plack::Util::Load and JSOe 

# Release Debian package via GitHub releases on tagged commits
before_deploy:
    - export RELEASE_FILE=$(ls *.deb)
    - echo "deploying $RELEASE_FILE to GitHub releases"
deploy:
    provider: releases
    api_key:
        secure: o9F+7dLe2rsjfn+OtHlUi7ARJFahtq59XMr6ah0KXcdCUe6Smq3qJTbBKxKUhqWkTTXESUTw89Dn2rbUreQmZFb3thpP8mvwQIHjSTsViP2Gp8HIgvhYdm1oCnQJSSUYJ1czJbOf2c4N65VICx0iaOLqT8egRTZsJhEewHpaIEo=
    file_glob: true
    file: "${RELEASE_FILE}"
    on:
        tags: true
