language: bash
sudo: false

# apt packages required to install CPAN packages 
addons:
    apt:
        packages:
            - libc6

services:
    - mongodb

before_script:
    - make local

script:
    - prove -v -Ilib
