language: bash
sudo: true

services:
    - mongodb

# install required packages on Ubuntu 12.04 which travis is still using
before_script:
    - sudo apt-get install libdancer-perl
      # catmandu requirements (incomplete)
    - sudo apt-get install libapp-cmd-perl libmodule-info-perl libyaml-libyaml-perl libjson-xs-perl libmoo-perl
    - sudo apt-get install libc6 # for marpa
    - make local

script:
    - prove -v -Ilib
