---
description: JSON Schema of cocoda-db config file
type: object
required: 
    - limit
    - endpoints
properties:

    port:
        type: array
        items:
            - type: string

    limit:
        type: object
        required:
            - default
            - max
        properties:
            default:
                type: integer
                minimum: 1
            max:
                type: integer
                minimum: 1

    title:
        type: string

    endpoints:
        type: object
        additionalProperties: false
        properties:
            concepts:
                type: object
                required:
                    - href
                properties:
                    href:
                        type: string
                    title:
                        type: string
            schemes:
                type: object
                required:
                    - href
                properties:
                    href:
                        type: string
                    title:
                        type: string
            types:
                type: object
                required:
                    - href
                properties:
                    href:
                        type: string
                    title:
                        type: string
            mappings:
                type: object
                required:
                    - href
                properties:
                    href:
                        type: string
                    title:
                        required: 0
                        type: string

    # catmandu config path
    catmandu:
        type: string

