---
###############################################################################
# cocoda-db config file
###############################################################################

# list of IPs or IP ranges to trust as proxy
proxy:
    - 127.0.0.1

# limit parameter for pagination
limit:
    default: 20
    max: 1000

# human-readble name of service
# title: "…"

# configuration of endpoints
# href MUST NOT start with '/' or './' (but possibly with '//')
# a human-readable title can be added with field 'title'
endpoints:
    concepts: 
        href: concepts
    schemes: 
        href: schemes
    types:
        href: types
    mappings:
        href: mappings


