#!/bin/sh
set -e

PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE"

case "$1" in
    remove)
        # Remove web application service
        update-rc.d -f $PACKAGE remove
    ;;

    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        echo "prerm argument $1 not implemented."
    ;;

    *)
        echo "prerm called with unknown argument: $1" >&2
        exit 1
    ;;
esac

exit 0
